import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider"
import { Geist, Geist_Mono } from "next/font/google";
import PushProvider from "@/components/PushProvider"
import LeaderboardProvider from "@/components/LeaderboardProvider"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm md:text-base`}
      >
        <ThemeProvider>
          <PushProvider /> 
           <LeaderboardProvider> {/* ✅ ADD THIS */}
            {children}
          </LeaderboardProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}